### ISSUE TITLE
 [US] As a repository owner, I want to be able to create a release filled with changelog using GitHub Action

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/cofy#16]
## Tasks:
- [x] Find a GitHub Action to create a release
- [x] Find a GitHub Action to fill the release body with changelogs
- [x] Create badge to the documentation
