### ISSUE TITLE
[US] As a developer, I want my API to have a User entity

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/cofy#2]
## Tasks:
- [ ] create User model mand controller
- [ ] stock a User in db
- [ ] create route to access to the User
