### ISSUE TITLE
[US] As a user, I want to have an inventory and can see it

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/cofy#23]
## Tasks:
- [ ] create Inventory struct + interface
- [ ] create Inventory command
- [ ] connect my Intenvory through API
