### ISSUE TITLE
[US] As a user, I want to have a profile and see it

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/cofy#24]
## Tasks:
- [ ] create Profile struct + interface
- [ ] create Profile command
- [ ] connect my Profile through API
