### ISSUE TITLE
[US] As a user, I want to be able to see the podium

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/cofy#26]
## Tasks:
- [ ] create Podium struct + interface
- [ ] create Podium command
- [ ] connect my Podium through API
