### ISSUE TITLE
 [US] As a developer, I want my API to have a Coffees entity and CRUD

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/cofy#27]
## Tasks:
- [ ] create Coffees model mand controller
- [ ] stock a Coffees in db
- [ ] create route to access to the Coffees
