### ISSUE TITLE
[US] As a developer, I want my API to have a Achievement entity and CRUD

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/cofy#28]
## Tasks:
- [ ] create Achievement model mand controller
- [ ] stock a Achievement in db
- [ ] create route to access to the Achievement
