### ISSUE TITLE
[US] As a developer, I want to connect to my API throught my discord bot

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/cofy#3]
## Tasks:
- [ ] use an ORM
- [ ] connect to db
- [ ] access to db
