### ISSUE TITLE
[US] As a user, I want to gain XP and CF each time I send a message #5 

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/cofy#6]
## Tasks:
- [ ] detect when a user send a message
- [ ] gain XP for each message
- [ ] gain CF for each message
- [ ] send request to API
