### ISSUE TITLE
[US] As a developer, I want my API to have a Coffee entity and CRUD

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/cofy#8]
## Tasks:
- [ ] create Coffee model and controller
- [ ] stock a coffee in db
- [ ] create route to access to the coffee
